apiVersion: v1
kind: Service
metadata:
  name: laboratorio-final-service
  labels:
    app: laboratorio-final-celula-movies
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31000
  selector:
    app: laboratorio-final-celula-movies
